// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjq6056F9gnpwYu_O0DC_rKscrDVYis7s',
    appId: '1:1068135496217:web:874170b470ba25bf9dc888',
    messagingSenderId: '1068135496217',
    projectId: 'rental-cars-2cbba',
    authDomain: 'rental-cars-2cbba.firebaseapp.com',
    storageBucket: 'rental-cars-2cbba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_QiA1gXpW4jPHVk5TL4wIwV11j83wjr8',
    appId: '1:1068135496217:android:0e27771a493cc7979dc888',
    messagingSenderId: '1068135496217',
    projectId: 'rental-cars-2cbba',
    storageBucket: 'rental-cars-2cbba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOnqJ2Jg9Uv-FFo7jb3oI9zJcpiMuqLEc',
    appId: '1:1068135496217:ios:cfb3ff4a2e4403859dc888',
    messagingSenderId: '1068135496217',
    projectId: 'rental-cars-2cbba',
    storageBucket: 'rental-cars-2cbba.firebasestorage.app',
    iosBundleId: 'com.example.rentalCars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOnqJ2Jg9Uv-FFo7jb3oI9zJcpiMuqLEc',
    appId: '1:1068135496217:ios:cfb3ff4a2e4403859dc888',
    messagingSenderId: '1068135496217',
    projectId: 'rental-cars-2cbba',
    storageBucket: 'rental-cars-2cbba.firebasestorage.app',
    iosBundleId: 'com.example.rentalCars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjq6056F9gnpwYu_O0DC_rKscrDVYis7s',
    appId: '1:1068135496217:web:629f4d836b4849df9dc888',
    messagingSenderId: '1068135496217',
    projectId: 'rental-cars-2cbba',
    authDomain: 'rental-cars-2cbba.firebaseapp.com',
    storageBucket: 'rental-cars-2cbba.firebasestorage.app',
  );

}